baseURL: http://localhost
projectName: EcoTrain
scenarios:
  - name: Consulter des résultats de recherche
    path: ./scenarios/consult_results.js
  - name: Consulter les détails d'un trajet
    path: ./scenarios/consult_details.js
  - name: Consulter ses billets
    path: ./scenarios/consult_tickets.js
  - name: Consulter les détauls d'un billet
    path: ./scenatios/consult_ticket_details.js

containers:
  - ecotrain-static_hosting-1
  - ecotrain-backend-1